import { TranslationSet, Language } from './types';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
];

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    welcome: "Welcome to AgriConnect",
    login: "Log In",
    signup: "Sign Up",
    logout: "Logout",
    logoutConfirm: "Are you sure you want to logout?",
    confirm: "Confirm",
    cancel: "Cancel",
    name: "Full Name",
    phone: "Phone Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "Passwords do not match",
    invalidPassword: "Incorrect password",
    location: "Location",
    alreadyAccount: "Already have an account? Log In",
    noAccount: "Don't have an account? Register",
    phoneExistsError: "Phone number already registered. Please Log In.",
    selectRole: "Who are you?",
    chooseRoleDesc: "Choose your role to continue registration.",
    farmer: "Farmer",
    farmerDesc: "Sell harvests, track sales, and manage finances.",
    vendor: "Vendor",
    vendorDesc: "Source fresh produce directly from farm gates.",
    community: "Community Member",
    communityDesc: "Bridge the gap for tech-less farmers & verify users.",
    completeProfile: "Complete Your Profile",
    profileGreeting: "Welcome! Just a few more details to set up your profile.",
    detailedLocation: "Detailed Location / Village",
    payoutInfo: "Payout Information",
    bankAccountNo: "Bank Account No.",
    ifscCode: "IFSC Code",
    completeReg: "Complete Registration",
    dashboard: "Dashboard",
    profile: "Profile & Portfolio",
    crops: "My Crops",
    myCrops: "My Crops",
    sellNew: "Sell New Crop",
    salesHistory: "Sales History",
    portfolio: "Portfolio",
    updateProfile: "Update Profile",
    cropName: "Crop Name",
    pricePerKg: "Price (per kg)",
    quantityAvail: "Quantity Available",
    cropImage: "Crop Image",
    uploadImage: "Upload Image",
    listCrop: "List Crop for Sale",
    stock: "Stock",
    marketplace: "Marketplace",
    searchCrops: "Search crops...",
    searchLocation: "Search location...",
    buyNow: "Buy Now",
    call: "Call",
    contactFarmer: "Contact Farmer",
    summaryPayments: "Summary & Payments",
    totalSpent: "Total Spent",
    receiptTitle: "Payment Receipt",
    amountPaid: "Amount Paid",
    orderId: "Order ID",
    delivery: "Delivery Mode",
    done: "Done",
    dateLabel: "Date",
    communityHub: "Community Hub",
    proxyReg: "Register Non-Tech Farmer",
    requests: "Verification Requests",
    verifyFarmer: "Verify Farmer",
    inYourArea: "In Your Area",
    outOfArea: "Out of Area",
    areaMismatch: "Location Mismatch",
    activeDirectory: "Verified Farmers",
    rating: "Rating",
    notifications: "Notifications",
    noNotifications: "All caught up!",
    markAllRead: "Clear All",
    trustScore: "Trust Score",
    paymentTitle: "Secure Payment",
    paySecurely: "Pay Securely via Platform",
    escrowNotice: "Funds will be held by AgriConnect and released to the farmer after successful delivery confirmation.",
    processing: "Processing UPI Payment...",
    paymentSuccess: "Payment Successful",
    heldByPlatform: "Held by Platform",
    releaseToFarmer: "Release Payment",
    paymentDisbursed: "Payment Disbursed to Farmer",
    deliveryTracking: "Delivery Tracking",
    shipped: "Shipped",
    inTransit: "In Transit",
    delivered: "Delivered",
    markAsShipped: "Mark as Shipped",
    trackingId: "Tracking ID",
    viewTracking: "Track Order",
    cropGuide: "Growth Guide",
    growthDuration: "Growth Duration",
    fertilizerNeeds: "Fertilizer Needs",
    soilRequirements: "Soil Requirements",
    idealTemp: "Ideal Temperature",
    growthStages: "Growth Stages",
    fetchingGuide: "Fetching expert guide...",
    farmingTips: "Farming Tips",
    expertAdvice: "Gemini Expert Advice",
    refreshTips: "Get New Tips",
    localizedFor: "Tips for",
    botGreeting: "Hello! I'm AgriBot. How can I help you today?",
    botInputPlaceholder: "Ask about farming...",
    soldOut: "Sold Out",
    vendorStrategy: "Strategy & Care",
    deliveryByAgri: "By AgriConnect",
    deliveryBySelf: "Self Transportation",
    maintenanceTips: "Maintenance & Freshness",
    sellingStrategy: "Selling Strategy",
    communityStrategy: "Community Strategy",
    myFarmers: "Managed Farmers",
    regionalVolume: "Regional Trade Volume",
  },
  hi: {
    welcome: "AgriConnect में आपका स्वागत है",
    login: "लॉग इन करें",
    signup: "साइन अप करें",
    logout: "लॉगआउट",
    logoutConfirm: "क्या आप वाकई लॉगआउट करना चाहते हैं?",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    name: "पूरा नाम",
    phone: "फ़ोन नंबर",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    passwordMismatch: "पासवर्ड मेल नहीं खाते",
    invalidPassword: "गलत पासवर्ड",
    location: "स्थान",
    alreadyAccount: "क्या आपके पास पहले से खाता है? लॉग इन करें",
    noAccount: "खाता नहीं है? पंजीकरण करें",
    phoneExistsError: "फ़ोन नंबर पहले से पंजीकृत है। कृपया लॉग इन करें।",
    selectRole: "आप कौन हैं?",
    chooseRoleDesc: "पंजीकरण जारी रखने के लिए अपनी भूमिका चुनें।",
    farmer: "किसान",
    farmerDesc: "फसल बेचें, बिक्री ट्रैक करें और वित्त प्रबंधित करें।",
    vendor: "विक्रेता",
    vendorDesc: "सीधे खेत से ताजा उत्पाद प्राप्त करें।",
    community: "समुदाय सदस्य",
    communityDesc: "तकनीक-मुक्त किसानों की मदद करें और उपयोगकर्ताओं को सत्यापित करें।",
    completeProfile: "अपनी प्रोफ़ाइल पूरी करें",
    profileGreeting: "स्वागत है! अपनी प्रोफ़ाइल सेट करने के लिए बस कुछ और विवरण।",
    detailedLocation: "विस्तृत स्थान / गाँव",
    payoutInfo: "भुगतान जानकारी",
    bankAccountNo: "बैंक खाता संख्या",
    ifscCode: "IFSC कोड",
    completeReg: "पंजीकरण पूरा करें",
    dashboard: "डैशबोर्ड",
    profile: "प्रोफ़ाइल और पोर्टफोलियो",
    crops: "मेरी फसलें",
    myCrops: "मेरी फसलें",
    sellNew: "नई फसल बेचें",
    salesHistory: "बिक्री इतिहास",
    portfolio: "पोर्टफोलियो",
    updateProfile: "प्रोफ़ाइल अपडेट करें",
    cropName: "फसल का नाम",
    pricePerKg: "कीमत (प्रति किलो)",
    quantityAvail: "उपलब्ध मात्रा",
    cropImage: "फसल की छवि",
    uploadImage: "छवि अपलोड करें",
    listCrop: "बिक्री के लिए फसल सूचीबद्ध करें",
    stock: "स्टॉक",
    marketplace: "बाजार",
    searchCrops: "फसलें खोजें...",
    searchLocation: "स्थान खोजें...",
    buyNow: "अभी खरीदें",
    call: "कॉल करें",
    contactFarmer: "किसान से संपर्क करें",
    summaryPayments: "सारांश और भुगतान",
    totalSpent: "कुल खर्च",
    receiptTitle: "भुगतान रसीद",
    amountPaid: "भुगतान की गई राशि",
    orderId: "ऑर्डर आईडी",
    delivery: "डिलिवरी मोड",
    done: "हो गया",
    dateLabel: "तारीख",
    communityHub: "समुदाय हब",
    proxyReg: "गैर-तकनीकी किसान को पंजीकृत करें",
    requests: "सत्यापन अनुरोध",
    verifyFarmer: "किसान सत्यापित करें",
    inYourArea: "आपके क्षेत्र में",
    outOfArea: "क्षेत्र से बाहर",
    areaMismatch: "स्थान बेमेल",
    activeDirectory: "सत्यापित किसान",
    rating: "रेटिंग",
    notifications: "सूचनाएं",
    noNotifications: "कोई नई सूचना नहीं!",
    markAllRead: "सब साफ़ करें",
    trustScore: "ट्रस्ट स्कोर",
    paymentTitle: "सुरक्षित भुगतान",
    paySecurely: "प्लेटफ़ॉर्म के माध्यम से भुगतान करें",
    escrowNotice: "धनराशि AgriConnect द्वारा सुरक्षित रखी जाएगी और सफल डिलीवरी के बाद किसान को दी जाएगी।",
    processing: "UPI भुगतान संसाधित हो रहा है...",
    paymentSuccess: "भुगतान सफल रहा",
    heldByPlatform: "प्लेटफ़ॉर्म के पास सुरक्षित",
    releaseToFarmer: "भुगतान जारी करें",
    paymentDisbursed: "किसान को भुगतान किया गया",
    deliveryTracking: "डिलीवरी ट्रैकिंग",
    shipped: "भेजा गया",
    inTransit: "रास्ते में",
    delivered: "पहुंचाया गया",
    markAsShipped: "भेजा गया चिह्नित करें",
    trackingId: "ट्रैकिंग आईडी",
    viewTracking: "ऑर्डर ट्रैक करें",
    cropGuide: "विकास गाइड",
    growthDuration: "विकास अवधि",
    fertilizerNeeds: "उर्वरक की आवश्यकता",
    soilRequirements: "मिट्टी की आवश्यकताएं",
    idealTemp: "आदर्श तापमान",
    growthStages: "विकास के चरण",
    fetchingGuide: "विशेषज्ञ गाइड प्राप्त कर रहे हैं...",
    farmingTips: "खेती के सुझाव",
    expertAdvice: "जेमिनी विशेषज्ञ सलाह",
    refreshTips: "नए सुझाव प्राप्त करें",
    localizedFor: "सुझाव यहाँ के लिए:",
    botGreeting: "नमस्ते! मैं एग्रीबॉट हूं। आज मैं आपकी क्या सहायता कर सकता हूं?",
    botInputPlaceholder: "खेती के बारे में पूछें...",
    soldOut: "बिक गया",
    vendorStrategy: "रणनीति और देखभाल",
    deliveryByAgri: "AgriConnect द्वारा",
    deliveryBySelf: "स्वयं परिवहन",
    maintenanceTips: "रखरखाव और ताजगी",
    sellingStrategy: "बिक्री रणनीति",
    communityStrategy: "सामुदायिक रणनीति",
    myFarmers: "प्रबंधित किसान",
    regionalVolume: "क्षेत्रीय व्यापार मात्रा",
  },
  te: {
    welcome: "AgriConnect కు స్వాగతం",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగ్ అవుట్",
    logoutConfirm: "మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?",
    confirm: "నిర్ధారించండి",
    cancel: "రద్దు చేయి",
    name: "పూర్తి పేరు",
    phone: "ఫోన్ నంబర్",
    password: "పాస్‌వర్డ్",
    confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
    passwordMismatch: "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
    invalidPassword: "తప్పు పాస్‌వర్డ్",
    location: "స్థలం",
    alreadyAccount: "ముందే ఖాతా ఉందా? లాగిన్ చేయండి",
    noAccount: "ఖాతా లేదా? నమోదు చేయండి",
    phoneExistsError: "ఫోన్ నంబర్ ఇప్పటికే నమోదైంది. దయచేసి లాగిన్ చేయండి.",
    selectRole: "మీరు ఎవరు?",
    chooseRoleDesc: "నమోదును కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి.",
    farmer: "రైతు",
    farmerDesc: "పంటలను అమ్మండి, అమ్మకాలను ట్రాక్ చేయండి.",
    vendor: "విక్రేత",
    vendorDesc: "తాజా ఉత్పత్తులను నేరుగా పొలాల నుండి పొందండి.",
    community: "కమ్యూనిటీ సభ్యుడు",
    communityDesc: "రైతులకు సహాయం చేయండి మరియు వినియోగదారులను ధృవీకరించండి.",
    completeProfile: "మీ ప్రొఫైల్ పూర్తి చేయండి",
    profileGreeting: "స్వాగతం! మీ ప్రొఫైల్ సెటప్ చేయడానికి మరికొన్ని వివరాలు.",
    detailedLocation: "వివరణాత్మక స్థానం / గ్రామం",
    payoutInfo: "చెల్లింపు సమాచారం",
    bankAccountNo: "బ్యాంక్ ఖాతా సంఖ్య",
    ifscCode: "IFSC కోడ్",
    completeReg: "నమోదు పూర్తి చేయండి",
    dashboard: "డాష్‌బోర్డ్",
    profile: "ప్రొఫైల్ & పోర్ట్‌ఫోలియో",
    crops: "నా పంటలు",
    myCrops: "నా పంటలు",
    sellNew: "కొత్త పంటను అమ్మండి",
    salesHistory: "అమ్మకాల చరిత్ర",
    portfolio: "పోర్ట్‌ఫోలియో",
    updateProfile: "ప్రొఫైల్ అప్‌డేట్ చేయండి",
    cropName: "పంట పేరు",
    pricePerKg: "ధర (కిలోకు)",
    quantityAvail: "అందుబాటులో ఉన్న పరిమాణం",
    cropImage: "పంట చిత్రం",
    uploadImage: "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    listCrop: "అమ్మకానికి పంటను జాబితా చేయండి",
    stock: "నిల్వ",
    marketplace: "మార్కెట్",
    searchCrops: "పంటల కోసం వెతకండి...",
    searchLocation: "స్థలం కోసం వెతకండి...",
    buyNow: "ఇప్పుడే కొనండి",
    call: "కాల్ చేయండి",
    contactFarmer: "రైతును సంప్రదించండి",
    summaryPayments: "సారాంశం & చెల్లింపులు",
    totalSpent: "మొత్తం ఖర్చు",
    receiptTitle: "చెల్లింపు రసీదు",
    amountPaid: "చెల్లించిన మొత్తం",
    orderId: "ఆర్డర్ ఐడి",
    delivery: "డెలివరీ విధానం",
    done: "ముగిసింది",
    dateLabel: "తేదీ",
    communityHub: "కమ్యూనిటీ హబ్",
    proxyReg: "రైతు నమోదు చేయండి",
    requests: "ధృవీకరణ అభ్యర్థనలు",
    verifyFarmer: "రైతును ధృవీకరించండి",
    inYourArea: "మీ ప్రాంతంలో",
    outOfArea: "ప్రాంతం బయట",
    areaMismatch: "స్థలం సరిపోలడం లేదు",
    activeDirectory: "ధృవీకరించబడిన రైతులు",
    rating: "రేటింగ్",
    notifications: "నోటిఫికేషన్లు",
    noNotifications: "నోటిఫికేషన్లు లేవు!",
    markAllRead: "అన్నీ తొలగించు",
    trustScore: "నమ్మక స్కోరు",
    paymentTitle: "సురక్షిత చెల్లింపు",
    paySecurely: "ప్లాట్‌ఫాం ద్వారా చెల్లించండి",
    escrowNotice: "AgriConnect ద్వారా నిధులు భద్రపరచబడతాయి మరియు డెలివరీ తర్వాత రైతుకు విడుదల చేయబడతాయి.",
    processing: "UPI చెల్లింపు ప్రాసెస్ అవుతోంది...",
    paymentSuccess: "చెల్లింపు విజయవంతమైంది",
    heldByPlatform: "ప్లాట్‌ఫాం వద్ద భద్రంగా ఉంది",
    releaseToFarmer: "చెల్లింపును విడుదల చేయండి",
    paymentDisbursed: "రైతుకు చెల్లింపు చేయబడింది",
    deliveryTracking: "డెలివరీ ట్రాకింగ్",
    shipped: "పంపబడింది",
    inTransit: "ప్రయాణంలో ఉంది",
    delivered: "పంపిణీ చేయబడింది",
    markAsShipped: "పంపినట్లు గుర్తించండి",
    trackingId: "ట్రాకింగ్ ఐడి",
    viewTracking: "ఆర్డర్ ట్రాక్ చేయండి",
    cropGuide: "పంట గైడ్",
    growthDuration: "పంట కాలం",
    fertilizerNeeds: "ఎరువుల అవసరాలు",
    soilRequirements: "నేల అవసరాలు",
    idealTemp: "అంతే ఉష్ణోగ్రత",
    growthStages: "వృద్ధి దశలు",
    fetchingGuide: "నిపుణుల గైడ్ పొందుతోంది...",
    farmingTips: "వ్యవసాయ చిట్కాలు",
    expertAdvice: "Gemini నిపుణుల సలహా",
    refreshTips: "కొత్త చిట్కాలు పొందండి",
    localizedFor: "దీని కోసం చిట్కాలు:",
    botGreeting: "హలో! నేను ఎగ్రీబాట్. ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?",
    botInputPlaceholder: "వ్యవసాయం గురించి అడగండి...",
    soldOut: "అమ్ముడైంది",
    vendorStrategy: "వ్యూహం & సంరక్షణ",
    deliveryByAgri: "AgriConnect ద్వారా",
    deliveryBySelf: "స్వంత రవాణా",
    maintenanceTips: "నిర్వహణ & తాజాదనం",
    sellingStrategy: "అమ్మకాల వ్యూహం",
    communityStrategy: "కమ్యూనిటీ వ్యూహం",
    myFarmers: "నిర్వహించే రైతులు",
    regionalVolume: "ప్రాంతీయ వాణిజ్య పరిమాణం",
  },
  ta: {
    welcome: "AgriConnect-க்கு வரவேற்கிறோம்",
    login: "உள்நுழைக",
    signup: "பதிவு செய்க",
    logout: "வெளியேறு",
    logoutConfirm: "நிச்சயமாக வெளியேற வேண்டுமா?",
    confirm: "உறுதிப்படுத்து",
    cancel: "ரத்து செய்",
    name: "முழு பெயர்",
    phone: "தொலைபேசி எண்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    passwordMismatch: "கடவுச்சொற்கள் பொருந்தவில்லை",
    invalidPassword: "தவறான கடவுச்சொல்",
    location: "இடம்",
    alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்",
    noAccount: "கணக்கு இல்லையா? பதிவு செய்யவும்",
    phoneExistsError: "தொலைபேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. தயவுசெய்து உள்நுழையவும்.",
    selectRole: "நீங்கள் யார்?",
    chooseRoleDesc: "பதிவைத் தொடர உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்.",
    farmer: "விவசாயி",
    farmerDesc: "விளைச்சலை விற்கவும், விற்பனையைக் கண்காணிக்கவும்.",
    vendor: "விற்பனையாளர்",
    vendorDesc: "புதிய விளைபொருட்களை நேரடியாக பண்ணைகளிலிருந்து பெறுங்கள்.",
    community: "சமூக உறுப்பினர்",
    communityDesc: "விவசாயிகளுக்கு உதவவும் மற்றும் பயனர்களைச் சரிபார்க்கவும்.",
    completeProfile: "உங்கள் சுயவிவரத்தை முடிக்கவும்",
    profileGreeting: "வரவேற்பு! உங்கள் சுயவிவரத்தை அமைக்க இன்னும் சில விவரங்கள்.",
    detailedLocation: "விரிவான இடம் / கிராமம்",
    payoutInfo: "பணம் செலுத்தும் தகவல்",
    bankAccountNo: "வங்கி கணக்கு எண்",
    ifscCode: "IFSC குறியீடு",
    completeReg: "பதிவை முடிக்கவும்",
    dashboard: "டாஷ்போர்டு",
    profile: "சுயவிவரம் மற்றும் போர்ட்ஃபோலியோ",
    crops: "எனது பயிர்கள்",
    myCrops: "எனது பயிர்கள்",
    sellNew: "புதிய பயிரை விற்கவும்",
    salesHistory: "விற்பனை வரலாறு",
    portfolio: "போர்ட்ஃபோலியோ",
    updateProfile: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
    cropName: "பயிரின் பெயர்",
    pricePerKg: "விலை (கிலோவிற்கு)",
    quantityAvail: "கிடைக்கும் அளவு",
    cropImage: "பயிர் படம்",
    uploadImage: "படத்தைப் பதிவேற்றவும்",
    listCrop: "விற்பனைக்கு பயிரைப் பட்டியலிடுங்கள்",
    stock: "இருப்பு",
    marketplace: "சந்தை",
    searchCrops: "பயிர்களைத் தேடுங்கள்...",
    searchLocation: "இடத்தைத் தேடுங்கள்...",
    buyNow: "இப்போதே வாங்கு",
    call: "அழைப்பு",
    contactFarmer: "விவசாயியைத் தொடர்பு கொள்ளவும்",
    summaryPayments: "சுருக்கம் மற்றும் கொடுப்பனவுகள்",
    totalSpent: "மொத்த செலவு",
    receiptTitle: "கட்டண ரசீது",
    amountPaid: "கட்டண ரசீது",
    orderId: "ஆர்டர் ஐடி",
    delivery: "டெலிவரி முறை",
    done: "முடிந்தது",
    dateLabel: "தேதி",
    communityHub: "சமூக மையம்",
    proxyReg: "விவசாயியைப் பதிவு செய்யவும்",
    requests: "சரிபார்ப்பு கோரிக்கைகள்",
    verifyFarmer: "விவசாயியைச் சரிபார்க்கவும்",
    inYourArea: "உங்கள் பகுதியில்",
    outOfArea: "பகுதிக்கு வெளியே",
    areaMismatch: "இடம் பொருந்தவில்லை",
    activeDirectory: "சரிபார்க்கப்பட்ட விவசாயிகள்",
    rating: "மதிப்பீடு",
    notifications: "அறிவிப்புகள்",
    noNotifications: "புதிய அறிவிப்புகள் இல்லை!",
    markAllRead: "அனைத்தையும் நீக்கு",
    trustScore: "நம்பிக்கை மதிப்பெண்",
    paymentTitle: "பாதுகாப்பான கட்டணம்",
    paySecurely: "தளம் மூலம் பாதுகாப்பாக செலுத்துங்கள்",
    escrowNotice: "நிதி AgriConnect ஆல் பாதுகாக்கப்படும் மற்றும் டெலிவரிக்கு பிறகு விவசாயியிடம் வழங்கப்படும்.",
    processing: "UPI கட்டணம் செயலாக்கப்படுகிறது...",
    paymentSuccess: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
    heldByPlatform: "தளத்தில் பாதுகாப்பாக உள்ளது",
    releaseToFarmer: "விவசாயிக்கு பணத்தை வழங்கு",
    paymentDisbursed: "விவசாயிக்கு பணம் செலுத்தப்பட்டது",
    deliveryTracking: "டெலிவரி கண்காணிப்பு",
    shipped: "அனுப்பப்பட்டது",
    inTransit: "வழியில் உள்ளது",
    delivered: "சேர்க்கப்பட்டது",
    markAsShipped: "அனுப்பப்பட்டது என குறிக்கவும்",
    trackingId: "கண்காணிப்பு ஐடி",
    viewTracking: "ஆர்டரை கண்காணிக்கவும்",
    cropGuide: "வளர்ச்சி வழிகாட்டி",
    growthDuration: "வளர்ச்சி காலம்",
    fertilizerNeeds: "உரத் தேவைகள்",
    soilRequirements: "மண் தேவைகள்",
    idealTemp: "சிறந்த வெப்பநிலை",
    growthStages: "வளர்ச்சி நிலைகள்",
    fetchingGuide: "நிபுணர் வழிகாட்டியைப் பெறுகிறது...",
    farmingTips: "விவசாய குறிப்புகள்",
    expertAdvice: "ஜெமினி நிபுணர் ஆலோசனை",
    refreshTips: "புதிய குறிப்புகளைப் பெறுக",
    localizedFor: "இதற்கான குறிப்புகள்:",
    botGreeting: "வணக்கம்! நான் அக்ரிபாட். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    botInputPlaceholder: "விவசாயம் பற்றி கேளுங்கள்...",
    soldOut: "விற்றுவிட்டது",
    vendorStrategy: "யுக்தி மற்றும் பராமரிப்பு",
    deliveryByAgri: "AgriConnect மூலம்",
    deliveryBySelf: "சுய போக்குவரத்து",
    maintenanceTips: "பராமரிப்பு மற்றும் புத்துணர்ச்சி",
    sellingStrategy: "விற்பனை உத்தி",
    communityStrategy: "சமூக உத்தி",
    myFarmers: "நிர்வகிக்கப்படும் விவசாயிகள்",
    regionalVolume: "வட்டார வர்த்தக அளவு",
  },
  kn: {
    welcome: "AgriConnect ಗೆ ಸುಸ್ವಾಗತ",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    logout: "ಲಾಗ್ ಔಟ್",
    logoutConfirm: "ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
    confirm: "ಖಚಿತಪಡಿಸಿ",
    cancel: "ರದ್ದುಗೊಳಿಸಿ",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ",
    passwordMismatch: "ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
    invalidPassword: "ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್",
    location: "ಸ್ಥಳ",
    alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಾಯಿಸಿ",
    phoneExistsError: "ಫೋನ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿದೆ. ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.",
    selectRole: "ನೀವು ಯಾರು?",
    chooseRoleDesc: "ನೋಂದಣಿ ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ.",
    farmer: "ರೈತ",
    farmerDesc: "ಬೆಳೆಗಳನ್ನು ಮಾರಾಟ ಮಾಡಿ, ಮಾರಾಟವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    vendor: "ಮಾರಾಟಗಾರ",
    vendorDesc: "ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ನೇರವಾಗಿ ಜಮೀನಿನಿಂದ ಪಡೆಯಿರಿ.",
    community: "ಸಮುದಾಯ ಸದಸ್ಯ",
    communityDesc: "ರೈತರನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಹಾಯ ಮಾಡಿ.",
    completeProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    profileGreeting: "ಸ್ವಾಗತ! ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಲು ಇನ್ನೂ ಕೆಲವು ವಿವರಗಳು.",
    detailedLocation: "ವಿವರವಾದ ಸ್ಥಳ / ಗ್ರಾಮ",
    payoutInfo: "ಪಾವತಿ ಮಾಹಿತಿ",
    bankAccountNo: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ",
    ifscCode: "IFSC ಕೋಡ್",
    completeReg: "ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ",
    dashboard: "ದಿನಚರಿ",
    profile: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಪೋರ್ಟ್‌ಫೋಲಿಯೋ",
    crops: "ನನ್ನ ಬೆಳೆಗಳು",
    myCrops: "ನನ್ನ ಬೆಳೆಗಳು",
    sellNew: "ಹೊಸ ಬೆಳೆಯನ್ನು ಮಾರಾಟ ಮಾಡಿ",
    salesHistory: "ಮಾರಾಟ ಇತಿಹಾಸ",
    portfolio: "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ",
    updateProfile: "ಪ್ರೊಫೈಲ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
    cropName: "ಬೆಳೆಯ ಹೆಸರು",
    pricePerKg: "ಬೆಲೆ (ಕೆಜಿಗೆ)",
    quantityAvail: "ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ",
    cropImage: "ಬೆಳೆಯ ಚಿತ್ರ",
    uploadImage: "ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    listCrop: "ಮಾರಾಟಕ್ಕೆ ಬೆಳೆಯನ್ನು ಪಟ್ಟಿ ಮಾಡಿ",
    stock: "ದಾಸ್ತಾನು",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    searchCrops: "ಬೆಳೆಗಳಿಗಾಗಿ ಹುಡುಕಿ...",
    searchLocation: "ಸ್ಥಳಕ್ಕಾಗಿ ಹುಡುಕಿ...",
    buyNow: "ಈಗ ಖರೀದಿಸಿ",
    call: "ಕರೆ ಮಾಡಿ",
    contactFarmer: "ರೈತರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    summaryPayments: "ಸಾರಾಂಶ ಮತ್ತು ಪಾವತಿಗಳು",
    totalSpent: "ಒಟ್ಟು ವೆಚ್ಚ",
    receiptTitle: "ಪಾವತಿ ರಶೀದಿ",
    amountPaid: "ಪಾವತಿಸಿದ ಮೊತ್ತ",
    orderId: "ಆರ್ಡರ್ ಐಡಿ",
    delivery: "ಡೆಲಿವರಿ ವಿಧಾನ",
    done: "ಮುಗಿದಿದೆ",
    dateLabel: "ದಿನಾಂಕ",
    communityHub: "ಸಮುದಾಯ ಕೇಂದ್ರ",
    proxyReg: "ರೈತರನ್ನು ನೋಂದಾಯಿಸಿ",
    requests: "ಪರಿಶೀಲನೆ ವಿನಂತಿಗಳು",
    verifyFarmer: "ರೈತರನ್ನು ಪರಿಶೀಲಿಸಿ",
    inYourArea: "ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ",
    outOfArea: "ಪ್ರದೇಶದ ಹೊರಗೆ",
    areaMismatch: "ಸ್ಥಳ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
    activeDirectory: "ಪರಿಶೀಲಿಸಿದ ರೈತರು",
    rating: "ರೇಟಿಂಗ್",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    noNotifications: "ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ!",
    markAllRead: "ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ",
    trustScore: "ನಂಬಿಕೆ ಸ್ಕೋರ್",
    paymentTitle: "ಸುರಕ್ಷಿತ ಪಾವತಿ",
    paySecurely: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಮೂಲಕ ಪಾವತಿ ಮಾಡಿ",
    escrowNotice: "AgriConnect ಮೂಲಕ ಹಣವನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲಾಗುತ್ತದೆ ಮತ್ತು ಡೆಲಿವರಿ ಆದ ನಂತರ ರೈತರಿಗೆ ನೀಡಲಾಗುತ್ತದೆ.",
    processing: "UPI ಪಾವತಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
    paymentSuccess: "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ",
    heldByPlatform: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಬಳಿ ಸುರಕ್ಷಿತವಾಗಿದೆ",
    releaseToFarmer: "ರೈತರಿಗೆ ಹಣ ಬಿಡುಗಡೆ ಮಾಡಿ",
    paymentDisbursed: "ರೈತರಿಗೆ ಹಣ ಪಾವತಿಸಲಾಗಿದೆ",
    deliveryTracking: "ಡೆಲಿವರಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    shipped: "ರವಾನಿಸಲಾಗಿದೆ",
    inTransit: "ದಾರಿಯಲ್ಲಿದೆ",
    delivered: "ತಲುಪಿಸಲಾಗಿದೆ",
    markAsShipped: "ರವಾನಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    trackingId: "ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿ",
    viewTracking: "ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    cropGuide: "ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ",
    growthDuration: "ಬೆಳೆಯ ಅವಧಿ",
    fertilizerNeeds: "ಎರುವುಗಳ ಅಗತ್ಯತೆ",
    soilRequirements: "ಮಣ್ಣಿನ ಅವಶ್ಯಕತೆಗಳು",
    idealTemp: "ಅತ್ಯುತ್ತಮ ತಾಪಮಾನ",
    growthStages: "ಬೆಳವಣಿಗೆಯ ಹಂತಗಳು",
    fetchingGuide: "ತಜ್ಞರ ಮಾರ್ಗದರ್ಶಿಯನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    farmingTips: "ಕೃಷಿ ಸಲಹೆಗಳು",
    expertAdvice: "ಜೆಮಿನಿ ತಜ್ಞರ ಸಲಹೆ",
    refreshTips: "ಹೊಸ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    localizedFor: "ಇದಕ್ಕಾಗಿ ಸಲಹೆಗಳು:",
    botGreeting: "ನಮಸ್ಕಾರ! ನಾನು ಅಗ್ರಿಬಾಟ್. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    botInputPlaceholder: "ಕೃಷಿಯ ಬಗ್ಗೆ ಕೇಳಿ...",
    soldOut: "ಮಾರಾಟವಾಗಿದೆ",
    vendorStrategy: "ಕಾರ್ಯತಂತ್ರ ಮತ್ತು ಆರೈಕೆ",
    deliveryByAgri: "AgriConnect ಮೂಲಕ",
    deliveryBySelf: "ಸ್ವಯಂ ಸಾರಿಗೆ",
    maintenanceTips: "ನಿರ್ವಹಣೆ ಮತ್ತು ತಾಜಾತನ",
    sellingStrategy: "ಮಾರಾಟ ಕಾರ್ಯತಂತ್ರ",
    communityStrategy: "ಸಮುದಾಯ ಕಾರ್ಯತಂತ್ರ",
    myFarmers: "ನಿರ್ವಹಿಸುವ ರೈತರು",
    regionalVolume: "ಪ್ರಾದೇಶಿಕ ವ್ಯಾಪಾರದ ಪ್ರಮಾಣ",
  }
};